---
- hosts: all #"{{survey_host}}"
  become: yes
  become_user: root
  # ignore_errors: yes
     
  tasks:
  - name: Include Clear-CPU-Usage
    include_role: 
     name: Clear-CPU-Usage

  post_tasks:
    - name: set stat
      set_stats:
        data:
          seum_status: complete
        aggregate: no
        per_host: no
      when:
        - cpu_fact == "complete"

    - name: set stat
      set_stats:
        data:
          seum_status: failed
        aggregate: no
        per_host: no
      when:
        - cpu_fact == "failed"
