---     
- name: Gathering managed nodes information
  shell: "hostname -i"
  register: ipout
  
- name: Gathering hostname information.
  shell: "uname -n"
  register: hostout
  
- name: Installing New packages
  yum:
          #security: yes
    name: "{{package_list}}"
    state: present #latest
    #exclude: kernel*
  register: install_results
  
  
- name: Package Details
  debug:
    msg: "{{package_list[1]}}"
  register: out_package
  
- name: set fact if COMPLETE
  set_fact:
   linux_patching_fact: "complete"
   cacheable: yes 
  when: install_results.rc  == 0
     
- name: set fact if FAILED.
  set_fact:
   linux_patching_fact: "failed"
   cacheable: yes     
  when: install_results.failed == true
    
- name: Importing Reporting-DB role
  import_role:
   name: Reporting-DB
